import type { CardDef, CardId } from '../types'

export const cardPool: CardDef[] = [
  { id: 'c01', name: 'Abu', top: 2, right: 2, bottom: 1, left: 2, rarity: 'common', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c02', name: 'Bourriquet', top: 2, right: 1, bottom: 1, left: 2, rarity: 'common', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c03', name: 'Fée Clochette', top: 2, right: 3, bottom: 1, left: 2, rarity: 'common', categoryId: 'disney', elementId: 'lumiere' },
  { id: 'c04', name: 'Picsou', top: 1, right: 2, bottom: 1, left: 3, rarity: 'common', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c05', name: 'Pluto', top: 2, right: 2, bottom: 2, left: 1, rarity: 'common', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c06', name: 'Porcinet', top: 1, right: 1, bottom: 2, left: 2, rarity: 'common', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c07', name: 'Sébastien', top: 1, right: 2, bottom: 2, left: 1, rarity: 'common', categoryId: 'disney', elementId: 'eau' },
  { id: 'c08', name: 'Tic et Tac', top: 1, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c09', name: 'Tigrou', top: 2, right: 3, bottom: 1, left: 1, rarity: 'common', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c10', name: 'Winnie', top: 1, right: 1, bottom: 2, left: 3, rarity: 'common', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c11', name: 'Bibi', top: 2, right: 1, bottom: 2, left: 2, rarity: 'common', categoryId: 'final_fantasy', elementId: 'feu' },
  { id: 'c12', name: 'Jiminy Cricket', top: 2, right: 2, bottom: 2, left: 1, rarity: 'common', categoryId: 'heros', elementId: 'neutre' },
  { id: 'c13', name: 'Archibombe', top: 1, right: 2, bottom: 3, left: 1, rarity: 'common', categoryId: 'nescient', elementId: 'feu' },
  { id: 'c14', name: 'Hareraiser', top: 1, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'nescient', elementId: 'neutre' },
  { id: 'c15', name: 'Inondation', top: 2, right: 1, bottom: 2, left: 2, rarity: 'common', categoryId: 'nescient', elementId: 'tenebres' },
  { id: 'c16', name: 'Monotruffe', top: 2, right: 2, bottom: 1, left: 3, rarity: 'common', categoryId: 'nescient', elementId: 'neutre' },
  { id: 'c17', name: 'Raclée', top: 3, right: 2, bottom: 1, left: 2, rarity: 'common', categoryId: 'nescient', elementId: 'neutre' },
  { id: 'c18', name: 'Scraper', top: 1, right: 3, bottom: 2, left: 1, rarity: 'common', categoryId: 'nescient', elementId: 'neutre' },
  { id: 'c19', name: 'Sonic Blaster', top: 3, right: 1, bottom: 1, left: 2, rarity: 'common', categoryId: 'nescient', elementId: 'vent' },
  { id: 'c20', name: 'Vile Phial', top: 2, right: 1, bottom: 1, left: 3, rarity: 'common', categoryId: 'nescient', elementId: 'poison' },
  { id: 'c21', name: 'Air Soldat', top: 3, right: 1, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'vent' },
  { id: 'c22', name: 'Aéro Soldat', top: 1, right: 2, bottom: 2, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'vent' },
  { id: 'c23', name: 'Ballade Rose', top: 1, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'soin' },
  { id: 'c24', name: 'Brute Volante', top: 1, right: 3, bottom: 1, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c25', name: 'Champignon Noir', top: 1, right: 1, bottom: 3, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c26', name: 'Concerto Émeraude', top: 2, right: 2, bottom: 1, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c27', name: 'Crapaud Acide', top: 2, right: 1, bottom: 3, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c28', name: 'Crescendo', top: 1, right: 2, bottom: 3, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'soin' },
  { id: 'c29', name: 'Flamme de Nuit', top: 3, right: 2, bottom: 1, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'feu' },
  { id: 'c30', name: 'Griffe Rapide', top: 1, right: 3, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c31', name: 'Guêpe Furieuse', top: 3, right: 2, bottom: 2, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'vent' },
  { id: 'c32', name: 'Larve Rampante', top: 2, right: 1, bottom: 3, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c33', name: 'Marin Nocturne', top: 2, right: 2, bottom: 3, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'eau' },
  { id: 'c34', name: 'Minute Bombe', top: 3, right: 1, bottom: 3, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'feu' },
  { id: 'c35', name: 'Nocturne Rouge', top: 2, right: 3, bottom: 1, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'feu' },
  { id: 'c36', name: 'Ombre', top: 2, right: 1, bottom: 2, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c37', name: 'Ombre Vivace', top: 2, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c38', name: 'Opéra Jaune', top: 1, right: 2, bottom: 2, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'foudre' },
  { id: 'c39', name: 'Pot Araignée', top: 1, right: 3, bottom: 2, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c40', name: 'Rabat-Joie', top: 2, right: 1, bottom: 1, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c41', name: 'Requiem Vert', top: 1, right: 2, bottom: 1, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'soin' },
  { id: 'c42', name: 'Rhapsodie Bleue', top: 2, right: 1, bottom: 3, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'glace' },
  { id: 'c43', name: 'Singe Bruyant', top: 2, right: 3, bottom: 2, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c44', name: 'Soldat', top: 3, right: 2, bottom: 1, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c45', name: 'Sonate Argentée', top: 2, right: 1, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c46', name: 'Surveillant', top: 3, right: 2, bottom: 2, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c47', name: 'Sérénade Turquoise', top: 1, right: 3, bottom: 1, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'glace' },
  { id: 'c48', name: 'Tornade', top: 2, right: 2, bottom: 1, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'vent' },
  { id: 'c49', name: 'Trio de l\'Ombre', top: 3, right: 1, bottom: 2, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c50', name: 'Éclair Lancier', top: 3, right: 2, bottom: 1, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'foudre' },
  { id: 'c51', name: 'Mushu', top: 4, right: 3, bottom: 2, left: 3, rarity: 'uncommon', categoryId: 'disney', elementId: 'feu' },
  { id: 'c52', name: 'Pat Hibulaire', top: 3, right: 4, bottom: 3, left: 2, rarity: 'uncommon', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c53', name: 'Tarzan', top: 4, right: 3, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c54', name: 'Cid', top: 3, right: 4, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'final_fantasy', elementId: 'neutre' },
  { id: 'c55', name: 'Selphie', top: 2, right: 3, bottom: 3, left: 4, rarity: 'uncommon', categoryId: 'final_fantasy', elementId: 'neutre' },
  { id: 'c56', name: 'Tidus', top: 3, right: 3, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'final_fantasy', elementId: 'eau' },
  { id: 'c57', name: 'Wakka', top: 4, right: 3, bottom: 2, left: 3, rarity: 'uncommon', categoryId: 'final_fantasy', elementId: 'neutre' },
  { id: 'c58', name: 'Hayner', top: 3, right: 3, bottom: 4, left: 2, rarity: 'uncommon', categoryId: 'heros', elementId: 'neutre' },
  { id: 'c59', name: 'Olette', top: 3, right: 4, bottom: 2, left: 3, rarity: 'uncommon', categoryId: 'heros', elementId: 'neutre' },
  { id: 'c60', name: 'Pence', top: 2, right: 3, bottom: 3, left: 4, rarity: 'uncommon', categoryId: 'heros', elementId: 'neutre' },
  { id: 'c61', name: 'Axe Flapper', top: 4, right: 2, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'nescient', elementId: 'vent' },
  { id: 'c62', name: 'Bruiser', top: 4, right: 3, bottom: 3, left: 2, rarity: 'uncommon', categoryId: 'nescient', elementId: 'neutre' },
  { id: 'c63', name: 'Chrono Twister', top: 3, right: 4, bottom: 2, left: 3, rarity: 'uncommon', categoryId: 'nescient', elementId: 'temps' },
  { id: 'c64', name: 'Mandrake', top: 3, right: 3, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'nescient', elementId: 'terre' },
  { id: 'c65', name: 'Tank Toppler', top: 2, right: 3, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'nescient', elementId: 'neutre' },
  { id: 'c66', name: 'Aquatank', top: 3, right: 2, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'eau' },
  { id: 'c67', name: 'Armure Sombre', top: 4, right: 2, bottom: 4, left: 2, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c68', name: 'Bandit', top: 3, right: 4, bottom: 2, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c69', name: 'Carapirate', top: 3, right: 4, bottom: 3, left: 2, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c70', name: 'Chamane Sombre', top: 3, right: 3, bottom: 4, left: 2, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c71', name: 'Champignon Blanc', top: 2, right: 3, bottom: 2, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'soin' },
  { id: 'c72', name: 'Fantôme', top: 3, right: 2, bottom: 3, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c73', name: 'Foudroyeur', top: 4, right: 3, bottom: 2, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'foudre' },
  { id: 'c74', name: 'Gargouille', top: 4, right: 3, bottom: 3, left: 2, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c75', name: 'Gros Ventre', top: 4, right: 2, bottom: 4, left: 2, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c76', name: 'Lance Soldat', top: 4, right: 2, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c77', name: 'Orbe Noir', top: 3, right: 3, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c78', name: 'Plongeur Vrille', top: 2, right: 4, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'eau' },
  { id: 'c79', name: 'Rapide Truffe', top: 2, right: 4, bottom: 2, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c80', name: 'Sorcière de Nuit', top: 3, right: 4, bottom: 3, left: 2, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c81', name: 'Taureau de Feu', top: 3, right: 4, bottom: 3, left: 2, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'feu' },
  { id: 'c82', name: 'Wyverne', top: 4, right: 3, bottom: 2, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'vent' },
  { id: 'c83', name: 'Éclaireur Sombre', top: 4, right: 3, bottom: 2, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c84', name: 'Assassin', top: 2, right: 4, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'simili', elementId: 'neutre' },
  { id: 'c85', name: 'Crétin', top: 3, right: 3, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'simili', elementId: 'neutre' },
  { id: 'c86', name: 'Danseur', top: 4, right: 3, bottom: 3, left: 2, rarity: 'uncommon', categoryId: 'simili', elementId: 'neutre' },
  { id: 'c87', name: 'Joueur', top: 3, right: 2, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'simili', elementId: 'neutre' },
  { id: 'c88', name: 'Reflet', top: 3, right: 3, bottom: 2, left: 4, rarity: 'uncommon', categoryId: 'simili', elementId: 'neutre' },
  { id: 'c89', name: 'Rôdeur', top: 2, right: 3, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'simili', elementId: 'neutre' },
  { id: 'c90', name: 'Sniper', top: 4, right: 4, bottom: 2, left: 2, rarity: 'uncommon', categoryId: 'simili', elementId: 'neutre' },
  { id: 'c91', name: 'Aladdin', top: 5, right: 4, bottom: 4, left: 5, rarity: 'rare', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c92', name: 'Ariel', top: 4, right: 3, bottom: 5, left: 5, rarity: 'rare', categoryId: 'disney', elementId: 'eau' },
  { id: 'c93', name: 'Hercule', top: 5, right: 5, bottom: 4, left: 4, rarity: 'rare', categoryId: 'disney', elementId: 'foudre' },
  { id: 'c94', name: 'Jack Skellington', top: 5, right: 4, bottom: 3, left: 5, rarity: 'rare', categoryId: 'disney', elementId: 'tenebres' },
  { id: 'c95', name: 'Jack Sparrow', top: 5, right: 5, bottom: 4, left: 4, rarity: 'rare', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c96', name: 'La Bête', top: 5, right: 5, bottom: 5, left: 3, rarity: 'rare', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c97', name: 'Mulan', top: 4, right: 5, bottom: 5, left: 4, rarity: 'rare', categoryId: 'disney', elementId: 'neutre' },
  { id: 'c98', name: 'Peter Pan', top: 4, right: 5, bottom: 3, left: 5, rarity: 'rare', categoryId: 'disney', elementId: 'vent' },
  { id: 'c99', name: 'Léon (Squall)', top: 5, right: 5, bottom: 4, left: 4, rarity: 'rare', categoryId: 'final_fantasy', elementId: 'neutre' },
  { id: 'c100', name: 'Youfie', top: 4, right: 5, bottom: 3, left: 5, rarity: 'rare', categoryId: 'final_fantasy', elementId: 'neutre' },
  { id: 'c101', name: 'Dingo', top: 5, right: 3, bottom: 5, left: 4, rarity: 'rare', categoryId: 'heros', elementId: 'neutre' },
  { id: 'c102', name: 'Donald', top: 4, right: 5, bottom: 3, left: 5, rarity: 'rare', categoryId: 'heros', elementId: 'feu' },
  { id: 'c103', name: 'Naminé', top: 4, right: 5, bottom: 5, left: 4, rarity: 'rare', categoryId: 'heros', elementId: 'lumiere' },
  { id: 'c104', name: 'Archiraven', top: 5, right: 4, bottom: 4, left: 4, rarity: 'rare', categoryId: 'nescient', elementId: 'vent' },
  { id: 'c105', name: 'Monstruosité', top: 4, right: 5, bottom: 5, left: 3, rarity: 'rare', categoryId: 'nescient', elementId: 'tenebres' },
  { id: 'c106', name: 'Ange Étoilé', top: 5, right: 5, bottom: 3, left: 4, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'lumiere' },
  { id: 'c107', name: 'Arraché-Cœur', top: 4, right: 5, bottom: 5, left: 3, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c108', name: 'Brûleur Mordant', top: 4, right: 4, bottom: 5, left: 5, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'feu' },
  { id: 'c109', name: 'Défenseur', top: 5, right: 3, bottom: 5, left: 4, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c110', name: 'Invisible', top: 5, right: 4, bottom: 4, left: 5, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c111', name: 'Mage Cramoisi', top: 3, right: 5, bottom: 5, left: 4, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'feu' },
  { id: 'c112', name: 'Nécromancie', top: 5, right: 3, bottom: 4, left: 5, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c113', name: 'Néo-Ombre', top: 5, right: 4, bottom: 5, left: 3, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c114', name: 'Sorcier', top: 4, right: 5, bottom: 3, left: 5, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'feu' },
  { id: 'c115', name: 'Spectre Fouineur', top: 3, right: 5, bottom: 4, left: 5, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c116', name: 'Berserker Simili', top: 5, right: 4, bottom: 3, left: 5, rarity: 'rare', categoryId: 'simili', elementId: 'neutre' },
  { id: 'c117', name: 'Mime Simili', top: 4, right: 4, bottom: 5, left: 4, rarity: 'rare', categoryId: 'simili', elementId: 'neutre' },
  { id: 'c118', name: 'Ninja Simili', top: 5, right: 3, bottom: 5, left: 4, rarity: 'rare', categoryId: 'simili', elementId: 'neutre' },
  { id: 'c119', name: 'Samouraï', top: 4, right: 5, bottom: 5, left: 3, rarity: 'rare', categoryId: 'simili', elementId: 'neutre' },
  { id: 'c120', name: 'Sorcier Simili', top: 3, right: 5, bottom: 4, left: 5, rarity: 'rare', categoryId: 'simili', elementId: 'neutre' },
  { id: 'c121', name: 'Elsa', top: 6, right: 7, bottom: 5, left: 7, rarity: 'epic', categoryId: 'disney', elementId: 'glace' },
  { id: 'c122', name: 'Simba', top: 6, right: 7, bottom: 5, left: 6, rarity: 'epic', categoryId: 'disney', elementId: 'feu' },
  { id: 'c123', name: 'Cloud', top: 7, right: 6, bottom: 6, left: 7, rarity: 'epic', categoryId: 'final_fantasy', elementId: 'neutre' },
  { id: 'c124', name: 'Zack', top: 6, right: 7, bottom: 5, left: 7, rarity: 'epic', categoryId: 'final_fantasy', elementId: 'neutre' },
  { id: 'c125', name: 'Kairi', top: 7, right: 6, bottom: 6, left: 7, rarity: 'epic', categoryId: 'heros', elementId: 'lumiere' },
  { id: 'c126', name: 'Lea (Axel)', top: 7, right: 7, bottom: 5, left: 6, rarity: 'epic', categoryId: 'heros', elementId: 'feu' },
  { id: 'c127', name: 'Maître Eraqus', top: 7, right: 6, bottom: 6, left: 7, rarity: 'epic', categoryId: 'heros', elementId: 'lumiere' },
  { id: 'c128', name: 'Terra', top: 7, right: 6, bottom: 7, left: 6, rarity: 'epic', categoryId: 'heros', elementId: 'terre' },
  { id: 'c129', name: 'Ventus', top: 6, right: 7, bottom: 6, left: 7, rarity: 'epic', categoryId: 'heros', elementId: 'vent' },
  { id: 'c130', name: 'Xion', top: 6, right: 7, bottom: 7, left: 6, rarity: 'epic', categoryId: 'heros', elementId: 'lumiere' },
  { id: 'c131', name: 'Axel', top: 6, right: 7, bottom: 5, left: 6, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'feu' },
  { id: 'c132', name: 'Demyx', top: 5, right: 6, bottom: 6, left: 7, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'eau' },
  { id: 'c133', name: 'Lexaeus', top: 7, right: 5, bottom: 7, left: 5, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'terre' },
  { id: 'c134', name: 'Luxord', top: 6, right: 6, bottom: 7, left: 5, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'temps' },
  { id: 'c135', name: 'Saïx', top: 7, right: 6, bottom: 6, left: 5, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'lune' },
  { id: 'c136', name: 'Vexen', top: 6, right: 6, bottom: 5, left: 7, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'glace' },
  { id: 'c137', name: 'Xaldin', top: 6, right: 5, bottom: 7, left: 6, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'vent' },
  { id: 'c138', name: 'Xemnas', top: 7, right: 6, bottom: 5, left: 7, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'neant' },
  { id: 'c139', name: 'Xigbar', top: 5, right: 7, bottom: 6, left: 6, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'espace' },
  { id: 'c140', name: 'Zexion', top: 5, right: 7, bottom: 6, left: 6, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'illusion' },
  { id: 'c141', name: 'Ansem, Chercheur de Ténèbres', top: 9, right: 8, bottom: 9, left: 8, rarity: 'legendary', categoryId: 'boss_kh', elementId: 'tenebres' },
  { id: 'c142', name: 'Maître Xehanort', top: 9, right: 10, bottom: 9, left: 9, rarity: 'legendary', categoryId: 'boss_kh', elementId: 'tenebres' },
  { id: 'c143', name: 'Vanitas', top: 8, right: 9, bottom: 8, left: 8, rarity: 'legendary', categoryId: 'boss_kh', elementId: 'tenebres' },
  { id: 'c144', name: 'Xemnas Final', top: 10, right: 9, bottom: 8, left: 10, rarity: 'legendary', categoryId: 'boss_kh', elementId: 'neant' },
  { id: 'c145', name: 'Séphiroth', top: 9, right: 9, bottom: 8, left: 8, rarity: 'legendary', categoryId: 'final_fantasy', elementId: 'tenebres' },
  { id: 'c146', name: 'Aqua', top: 8, right: 8, bottom: 9, left: 8, rarity: 'legendary', categoryId: 'heros', elementId: 'lumiere' },
  { id: 'c147', name: 'Riku', top: 8, right: 9, bottom: 9, left: 8, rarity: 'legendary', categoryId: 'heros', elementId: 'aube' },
  { id: 'c148', name: 'Roi Mickey', top: 9, right: 7, bottom: 8, left: 9, rarity: 'legendary', categoryId: 'heros', elementId: 'lumiere' },
  { id: 'c149', name: 'Roxas', top: 9, right: 9, bottom: 7, left: 8, rarity: 'legendary', categoryId: 'heros', elementId: 'lumiere' },
  { id: 'c150', name: 'Sora', top: 9, right: 8, bottom: 8, left: 9, rarity: 'legendary', categoryId: 'heros', elementId: 'lumiere' },
]

export const cardById: Record<CardId, CardDef> = Object.fromEntries(cardPool.map((card) => [card.id, card]))

export function getCard(cardId: CardId): CardDef {
  const card = cardById[cardId]
  if (!card) {
    throw new Error(`Unknown card: ${cardId}`)
  }
  return card
}
