import type { CardDef, CardId } from '../types'


export const cardPool: CardDef[] = [
  { id: 'c01', name: 'Bulbizarre', top: 2, right: 3, bottom: 2, left: 2, rarity: 'common', categoryId: 'humain', elementId: 'plante' },
  { id: 'c02', name: 'Salamèche', top: 3, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'nescient', elementId: 'feu' },
  { id: 'c03', name: 'Carapuce', top: 2, right: 2, bottom: 3, left: 2, rarity: 'common', categoryId: 'humain', elementId: 'eau' },
  { id: 'c04', name: 'Chenipan', top: 1, right: 2, bottom: 2, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'insecte' },
  { id: 'c05', name: 'Chrysacier', top: 1, right: 1, bottom: 3, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'insecte' },
  { id: 'c06', name: 'Aspicot', top: 2, right: 1, bottom: 1, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'insecte' },
  { id: 'c07', name: 'Coconfort', top: 1, right: 2, bottom: 1, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'insecte' },
  { id: 'c08', name: 'Roucool', top: 2, right: 2, bottom: 1, left: 2, rarity: 'common', categoryId: 'simili', elementId: 'vol' },
  { id: 'c09', name: 'Rattata', top: 3, right: 2, bottom: 1, left: 2, rarity: 'common', categoryId: 'simili', elementId: 'normal' },
  { id: 'c10', name: 'Piafabec', top: 2, right: 3, bottom: 1, left: 1, rarity: 'common', categoryId: 'simili', elementId: 'vol' },
  { id: 'c11', name: 'Abo', top: 2, right: 1, bottom: 2, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c12', name: 'Pikachu', top: 3, right: 3, bottom: 2, left: 2, rarity: 'common', categoryId: 'nescient', elementId: 'electrik' },
  { id: 'c13', name: 'Sabelette', top: 2, right: 1, bottom: 3, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'sol' },
  { id: 'c14', name: 'Nidoran♀', top: 2, right: 2, bottom: 1, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c15', name: 'Nidoran♂', top: 2, right: 2, bottom: 2, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c16', name: 'Mélofée', top: 1, right: 2, bottom: 2, left: 3, rarity: 'common', categoryId: 'simili', elementId: 'normal' },
  { id: 'c17', name: 'Goupix', top: 2, right: 3, bottom: 1, left: 2, rarity: 'common', categoryId: 'nescient', elementId: 'feu' },
  { id: 'c18', name: 'Rondoudou', top: 1, right: 2, bottom: 3, left: 2, rarity: 'common', categoryId: 'simili', elementId: 'normal' },
  { id: 'c19', name: 'Nosferapti', top: 2, right: 2, bottom: 1, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c20', name: 'Mystherbe', top: 1, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'humain', elementId: 'plante' },
  { id: 'c21', name: 'Paras', top: 2, right: 1, bottom: 3, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'insecte' },
  { id: 'c22', name: 'Mimitoss', top: 1, right: 3, bottom: 1, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'insecte' },
  { id: 'c23', name: 'Taupiqueur', top: 3, right: 1, bottom: 1, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'sol' },
  { id: 'c24', name: 'Miaouss', top: 2, right: 3, bottom: 1, left: 2, rarity: 'common', categoryId: 'simili', elementId: 'normal' },
  { id: 'c25', name: 'Psykokwak', top: 2, right: 1, bottom: 2, left: 3, rarity: 'common', categoryId: 'humain', elementId: 'eau' },
  { id: 'c26', name: 'Férosinge', top: 3, right: 2, bottom: 1, left: 2, rarity: 'common', categoryId: 'nescient', elementId: 'combat' },
  { id: 'c27', name: 'Ptitard', top: 1, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'humain', elementId: 'eau' },
  { id: 'c28', name: 'Abra', top: 1, right: 1, bottom: 1, left: 4, rarity: 'common', categoryId: 'simili', elementId: 'psy' },
  { id: 'c29', name: 'Machoc', top: 3, right: 2, bottom: 2, left: 1, rarity: 'common', categoryId: 'nescient', elementId: 'combat' },
  { id: 'c30', name: 'Chétiflor', top: 1, right: 2, bottom: 1, left: 3, rarity: 'common', categoryId: 'humain', elementId: 'plante' },
  { id: 'c31', name: 'Tentacool', top: 2, right: 2, bottom: 1, left: 3, rarity: 'common', categoryId: 'humain', elementId: 'eau' },
  { id: 'c32', name: 'Racaillou', top: 2, right: 1, bottom: 3, left: 2, rarity: 'common', categoryId: 'nescient', elementId: 'roche' },
  { id: 'c33', name: 'Ponyta', top: 3, right: 2, bottom: 2, left: 1, rarity: 'common', categoryId: 'nescient', elementId: 'feu' },
  { id: 'c34', name: 'Ramoloss', top: 1, right: 2, bottom: 3, left: 2, rarity: 'common', categoryId: 'simili', elementId: 'psy' },
  { id: 'c35', name: 'Magnéti', top: 2, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'nescient', elementId: 'electrik' },
  { id: 'c36', name: 'Doduo', top: 2, right: 3, bottom: 1, left: 2, rarity: 'common', categoryId: 'simili', elementId: 'vol' },
  { id: 'c37', name: 'Otaria', top: 2, right: 1, bottom: 3, left: 2, rarity: 'common', categoryId: 'humain', elementId: 'eau' },
  { id: 'c38', name: 'Tadmorv', top: 2, right: 2, bottom: 3, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c39', name: 'Kokiyas', top: 1, right: 1, bottom: 4, left: 1, rarity: 'common', categoryId: 'humain', elementId: 'eau' },
  { id: 'c40', name: 'Fantominus', top: 1, right: 3, bottom: 1, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'spectre' },
  { id: 'c41', name: 'Soporifik', top: 2, right: 1, bottom: 2, left: 3, rarity: 'common', categoryId: 'simili', elementId: 'psy' },
  { id: 'c42', name: 'Krabby', top: 3, right: 2, bottom: 1, left: 2, rarity: 'common', categoryId: 'humain', elementId: 'eau' },
  { id: 'c43', name: 'Voltorbe', top: 2, right: 2, bottom: 1, left: 3, rarity: 'common', categoryId: 'nescient', elementId: 'electrik' },
  { id: 'c44', name: 'Noeunoeuf', top: 1, right: 2, bottom: 2, left: 3, rarity: 'common', categoryId: 'humain', elementId: 'plante' },
  { id: 'c45', name: 'Osselait', top: 2, right: 3, bottom: 2, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'sol' },
  { id: 'c46', name: 'Smogo', top: 2, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c47', name: 'Rhinocorne', top: 3, right: 1, bottom: 2, left: 2, rarity: 'common', categoryId: 'nescient', elementId: 'roche' },
  { id: 'c48', name: 'Hypotrempe', top: 1, right: 3, bottom: 2, left: 1, rarity: 'common', categoryId: 'humain', elementId: 'eau' },
  { id: 'c49', name: 'Poissirène', top: 2, right: 2, bottom: 1, left: 3, rarity: 'common', categoryId: 'humain', elementId: 'eau' },
  { id: 'c50', name: 'Magicarpe', top: 1, right: 1, bottom: 1, left: 1, rarity: 'common', categoryId: 'humain', elementId: 'eau' },
  { id: 'c51', name: 'Minidraco', top: 2, right: 3, bottom: 2, left: 2, rarity: 'common', categoryId: 'simili', elementId: 'dragon' },
  { id: 'c52', name: 'Herbizarre', top: 3, right: 4, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'humain', elementId: 'plante' },
  { id: 'c53', name: 'Reptincel', top: 4, right: 3, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'nescient', elementId: 'feu' },
  { id: 'c54', name: 'Carabaffe', top: 3, right: 3, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'humain', elementId: 'eau' },
  { id: 'c55', name: 'Papilusion', top: 3, right: 4, bottom: 2, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'insecte' },
  { id: 'c56', name: 'Dardargnan', top: 4, right: 3, bottom: 2, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'insecte' },
  { id: 'c57', name: 'Roucoups', top: 3, right: 4, bottom: 2, left: 3, rarity: 'uncommon', categoryId: 'simili', elementId: 'vol' },
  { id: 'c58', name: 'Rattatac', top: 4, right: 3, bottom: 2, left: 4, rarity: 'uncommon', categoryId: 'simili', elementId: 'normal' },
  { id: 'c59', name: 'Rapasdepic', top: 3, right: 4, bottom: 2, left: 3, rarity: 'uncommon', categoryId: 'simili', elementId: 'vol' },
  { id: 'c60', name: 'Arbok', top: 3, right: 2, bottom: 3, left: 5, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c61', name: 'Nidorina', top: 3, right: 3, bottom: 3, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c62', name: 'Nidorino', top: 3, right: 4, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c63', name: 'Grodoudou', top: 2, right: 3, bottom: 4, left: 4, rarity: 'uncommon', categoryId: 'simili', elementId: 'normal' },
  { id: 'c64', name: 'Nosferalto', top: 3, right: 4, bottom: 2, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c65', name: 'Ortide', top: 3, right: 3, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'humain', elementId: 'plante' },
  { id: 'c66', name: 'Triopikeur', top: 5, right: 2, bottom: 2, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'sol' },
  { id: 'c67', name: 'Caninos', top: 4, right: 3, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'nescient', elementId: 'feu' },
  { id: 'c68', name: 'Têtarte', top: 3, right: 3, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'humain', elementId: 'eau' },
  { id: 'c69', name: 'Kadabra', top: 2, right: 5, bottom: 2, left: 4, rarity: 'uncommon', categoryId: 'simili', elementId: 'psy' },
  { id: 'c70', name: 'Machopeur', top: 4, right: 3, bottom: 4, left: 2, rarity: 'uncommon', categoryId: 'nescient', elementId: 'combat' },
  { id: 'c71', name: 'Boustiflor', top: 3, right: 4, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'humain', elementId: 'plante' },
  { id: 'c72', name: 'Gravalanch', top: 3, right: 2, bottom: 5, left: 3, rarity: 'uncommon', categoryId: 'nescient', elementId: 'roche' },
  { id: 'c73', name: 'Canarticho', top: 3, right: 4, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'simili', elementId: 'vol' },
  { id: 'c74', name: 'Spectrum', top: 3, right: 4, bottom: 2, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'spectre' },
  { id: 'c75', name: 'Onix', top: 4, right: 2, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'nescient', elementId: 'roche' },
  { id: 'c76', name: 'Krabboss', top: 5, right: 3, bottom: 2, left: 3, rarity: 'uncommon', categoryId: 'humain', elementId: 'eau' },
  { id: 'c77', name: 'Électrode', top: 3, right: 4, bottom: 2, left: 4, rarity: 'uncommon', categoryId: 'nescient', elementId: 'electrik' },
  { id: 'c78', name: 'Kicklee', top: 4, right: 2, bottom: 3, left: 4, rarity: 'uncommon', categoryId: 'nescient', elementId: 'combat' },
  { id: 'c79', name: 'Tygnon', top: 3, right: 5, bottom: 2, left: 3, rarity: 'uncommon', categoryId: 'nescient', elementId: 'combat' },
  { id: 'c80', name: 'Excelangue', top: 3, right: 2, bottom: 4, left: 4, rarity: 'uncommon', categoryId: 'simili', elementId: 'normal' },
  { id: 'c81', name: 'Leveinard', top: 2, right: 3, bottom: 4, left: 4, rarity: 'uncommon', categoryId: 'simili', elementId: 'normal' },
  { id: 'c82', name: 'Saquedeneu', top: 3, right: 3, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'humain', elementId: 'plante' },
  { id: 'c83', name: 'Hypocéan', top: 3, right: 4, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'humain', elementId: 'eau' },
  { id: 'c84', name: 'Poissoroy', top: 3, right: 3, bottom: 3, left: 4, rarity: 'uncommon', categoryId: 'humain', elementId: 'eau' },
  { id: 'c85', name: 'Stari', top: 3, right: 3, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'humain', elementId: 'eau' },
  { id: 'c86', name: 'Métamorph', top: 3, right: 3, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'simili', elementId: 'normal' },
  { id: 'c87', name: 'Évoli', top: 3, right: 3, bottom: 3, left: 4, rarity: 'uncommon', categoryId: 'simili', elementId: 'normal' },
  { id: 'c88', name: 'Porygon', top: 4, right: 3, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'simili', elementId: 'normal' },
  { id: 'c89', name: 'Amonita', top: 2, right: 3, bottom: 4, left: 4, rarity: 'uncommon', categoryId: 'nescient', elementId: 'roche' },
  { id: 'c90', name: 'Kabuto', top: 3, right: 4, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'nescient', elementId: 'roche' },
  { id: 'c91', name: 'Draco', top: 4, right: 4, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'simili', elementId: 'dragon' },
  { id: 'c92', name: 'Roucarnage', top: 5, right: 5, bottom: 3, left: 5, rarity: 'rare', categoryId: 'simili', elementId: 'vol' },
  { id: 'c93', name: 'Raichu', top: 5, right: 6, bottom: 3, left: 5, rarity: 'rare', categoryId: 'nescient', elementId: 'electrik' },
  { id: 'c94', name: 'Sablaireau', top: 4, right: 3, bottom: 6, left: 5, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'sol' },
  { id: 'c95', name: 'Mélodelfe', top: 4, right: 5, bottom: 5, left: 5, rarity: 'rare', categoryId: 'simili', elementId: 'normal' },
  { id: 'c96', name: 'Rafflesia', top: 5, right: 4, bottom: 5, left: 4, rarity: 'rare', categoryId: 'humain', elementId: 'plante' },
  { id: 'c97', name: 'Parasect', top: 4, right: 3, bottom: 6, left: 5, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'insecte' },
  { id: 'c98', name: 'Aéromite', top: 4, right: 5, bottom: 3, left: 6, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c99', name: 'Persian', top: 5, right: 5, bottom: 3, left: 5, rarity: 'rare', categoryId: 'simili', elementId: 'normal' },
  { id: 'c100', name: 'Akwakwak', top: 4, right: 5, bottom: 4, left: 5, rarity: 'rare', categoryId: 'humain', elementId: 'eau' },
  { id: 'c101', name: 'Colossinge', top: 5, right: 5, bottom: 3, left: 5, rarity: 'rare', categoryId: 'nescient', elementId: 'combat' },
  { id: 'c102', name: 'Tartard', top: 5, right: 4, bottom: 5, left: 4, rarity: 'rare', categoryId: 'nescient', elementId: 'combat' },
  { id: 'c103', name: 'Empiflor', top: 5, right: 5, bottom: 4, left: 5, rarity: 'rare', categoryId: 'humain', elementId: 'plante' },
  { id: 'c104', name: 'Tentacruel', top: 4, right: 5, bottom: 5, left: 5, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c105', name: 'Grolem', top: 5, right: 3, bottom: 6, left: 5, rarity: 'rare', categoryId: 'nescient', elementId: 'roche' },
  { id: 'c106', name: 'Galopa', top: 6, right: 4, bottom: 3, left: 5, rarity: 'rare', categoryId: 'nescient', elementId: 'feu' },
  { id: 'c107', name: 'Dodrio', top: 5, right: 5, bottom: 3, left: 5, rarity: 'rare', categoryId: 'simili', elementId: 'vol' },
  { id: 'c108', name: 'Lamantine', top: 4, right: 4, bottom: 6, left: 4, rarity: 'rare', categoryId: 'humain', elementId: 'eau' },
  { id: 'c109', name: 'Ectoplasma', top: 4, right: 6, bottom: 3, left: 6, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'spectre' },
  { id: 'c110', name: 'Hypnomade', top: 4, right: 5, bottom: 5, left: 5, rarity: 'rare', categoryId: 'simili', elementId: 'psy' },
  { id: 'c111', name: 'Noadkoko', top: 5, right: 4, bottom: 5, left: 5, rarity: 'rare', categoryId: 'humain', elementId: 'plante' },
  { id: 'c112', name: 'Ossatueur', top: 5, right: 6, bottom: 4, left: 4, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'sol' },
  { id: 'c113', name: 'Smogogo', top: 4, right: 4, bottom: 5, left: 5, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c114', name: 'Rhinoféros', top: 6, right: 3, bottom: 5, left: 4, rarity: 'rare', categoryId: 'nescient', elementId: 'roche' },
  { id: 'c115', name: 'M. Mime', top: 3, right: 5, bottom: 5, left: 6, rarity: 'rare', categoryId: 'simili', elementId: 'psy' },
  { id: 'c116', name: 'Insécateur', top: 6, right: 5, bottom: 3, left: 5, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'insecte' },
  { id: 'c117', name: 'Lippoutou', top: 4, right: 5, bottom: 4, left: 6, rarity: 'rare', categoryId: 'simili', elementId: 'psy' },
  { id: 'c118', name: 'Scarabrute', top: 6, right: 4, bottom: 4, left: 5, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'insecte' },
  { id: 'c119', name: 'Tauros', top: 5, right: 5, bottom: 4, left: 5, rarity: 'rare', categoryId: 'simili', elementId: 'normal' },
  { id: 'c120', name: 'Amonistar', top: 4, right: 5, bottom: 6, left: 4, rarity: 'rare', categoryId: 'nescient', elementId: 'roche' },
  { id: 'c121', name: 'Kabutops', top: 6, right: 5, bottom: 3, left: 5, rarity: 'rare', categoryId: 'nescient', elementId: 'roche' },
  { id: 'c122', name: 'Florizarre', top: 6, right: 7, bottom: 6, left: 6, rarity: 'epic', categoryId: 'humain', elementId: 'plante' },
  { id: 'c123', name: 'Dracaufeu', top: 7, right: 7, bottom: 5, left: 6, rarity: 'epic', categoryId: 'nescient', elementId: 'feu' },
  { id: 'c124', name: 'Tortank', top: 6, right: 6, bottom: 7, left: 6, rarity: 'epic', categoryId: 'humain', elementId: 'eau' },
  { id: 'c125', name: 'Nidoqueen', top: 6, right: 5, bottom: 7, left: 6, rarity: 'epic', categoryId: 'sans_coeur', elementId: 'sol' },
  { id: 'c126', name: 'Nidoking', top: 7, right: 6, bottom: 5, left: 6, rarity: 'epic', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c127', name: 'Feunard', top: 6, right: 7, bottom: 5, left: 7, rarity: 'epic', categoryId: 'nescient', elementId: 'feu' },
  { id: 'c128', name: 'Arcanin', top: 7, right: 6, bottom: 6, left: 6, rarity: 'epic', categoryId: 'nescient', elementId: 'feu' },
  { id: 'c129', name: 'Alakazam', top: 5, right: 8, bottom: 4, left: 8, rarity: 'epic', categoryId: 'simili', elementId: 'psy' },
  { id: 'c130', name: 'Mackogneur', top: 7, right: 7, bottom: 6, left: 5, rarity: 'epic', categoryId: 'nescient', elementId: 'combat' },
  { id: 'c131', name: 'Flagadoss', top: 5, right: 6, bottom: 7, left: 6, rarity: 'epic', categoryId: 'simili', elementId: 'psy' },
  { id: 'c132', name: 'Magnéton', top: 6, right: 7, bottom: 5, left: 7, rarity: 'epic', categoryId: 'nescient', elementId: 'electrik' },
  { id: 'c133', name: 'Grotadmorv', top: 6, right: 5, bottom: 7, left: 6, rarity: 'epic', categoryId: 'sans_coeur', elementId: 'poison' },
  { id: 'c134', name: 'Crustabri', top: 5, right: 5, bottom: 8, left: 6, rarity: 'epic', categoryId: 'humain', elementId: 'glace' },
  { id: 'c135', name: 'Kangourex', top: 6, right: 6, bottom: 6, left: 7, rarity: 'epic', categoryId: 'simili', elementId: 'normal' },
  { id: 'c136', name: 'Staross', top: 6, right: 7, bottom: 6, left: 6, rarity: 'epic', categoryId: 'humain', elementId: 'eau' },
  { id: 'c137', name: 'Élektek', top: 7, right: 6, bottom: 5, left: 7, rarity: 'epic', categoryId: 'nescient', elementId: 'electrik' },
  { id: 'c138', name: 'Magmar', top: 6, right: 7, bottom: 6, left: 5, rarity: 'epic', categoryId: 'nescient', elementId: 'feu' },
  { id: 'c139', name: 'Lokhlass', top: 6, right: 5, bottom: 7, left: 7, rarity: 'epic', categoryId: 'humain', elementId: 'eau' },
  { id: 'c140', name: 'Ptéra', top: 7, right: 7, bottom: 4, left: 7, rarity: 'epic', categoryId: 'nescient', elementId: 'roche' },
  { id: 'c141', name: 'Ronflex', top: 5, right: 5, bottom: 8, left: 7, rarity: 'epic', categoryId: 'simili', elementId: 'normal' },
  { id: 'c142', name: 'Léviator', top: 8, right: 7, bottom: 7, left: 9, rarity: 'legendary', categoryId: 'humain', elementId: 'eau' },
  { id: 'c143', name: 'Aquali', top: 7, right: 8, bottom: 9, left: 7, rarity: 'legendary', categoryId: 'humain', elementId: 'eau' },
  { id: 'c144', name: 'Voltali', top: 9, right: 8, bottom: 6, left: 8, rarity: 'legendary', categoryId: 'nescient', elementId: 'electrik' },
  { id: 'c145', name: 'Pyroli', top: 8, right: 9, bottom: 7, left: 7, rarity: 'legendary', categoryId: 'nescient', elementId: 'feu' },
  { id: 'c146', name: 'Artikodin', top: 8, right: 7, bottom: 9, left: 8, rarity: 'legendary', categoryId: 'humain', elementId: 'glace' },
  { id: 'c147', name: 'Électhor', top: 9, right: 8, bottom: 7, left: 8, rarity: 'legendary', categoryId: 'nescient', elementId: 'electrik' },
  { id: 'c148', name: 'Sulfura', top: 8, right: 9, bottom: 7, left: 8, rarity: 'legendary', categoryId: 'nescient', elementId: 'feu' },
  { id: 'c149', name: 'Dracolosse', top: 8, right: 8, bottom: 8, left: 9, rarity: 'legendary', categoryId: 'simili', elementId: 'dragon' },
  { id: 'c150', name: 'Mewtwo', top: 9, right: 10, bottom: 7, left: 9, rarity: 'legendary', categoryId: 'sans_coeur', elementId: 'psy' },
  { id: 'c151', name: 'Mew', top: 8, right: 8, bottom: 8, left: 8, rarity: 'legendary', categoryId: 'simili', elementId: 'psy' },
]

export const cardById: Record<CardId, CardDef> = Object.fromEntries(cardPool.map((card) => [card.id, card]))

export function getCard(cardId: CardId): CardDef {
  const card = cardById[cardId]
  if (!card) {
    throw new Error(`Unknown card: ${cardId}`)
  }
  return card
}

