import type { CardDef, CardId } from '../types'

export const cardPool: CardDef[] = [
  { id: 'c01', name: 'Sora (Forme Ultime)', top: 10, right: 9, bottom: 8, left: 9, rarity: 'legendary', categoryId: 'porteur_de_keyblade', elementId: 'lumiere' },
  { id: 'c02', name: 'Maître Xehanort', top: 9, right: 10, bottom: 9, left: 8, rarity: 'legendary', categoryId: 'antagoniste', elementId: 'tenebres' },
  { id: 'c03', name: 'Kingdom Hearts', top: 10, right: 10, bottom: 10, left: 7, rarity: 'legendary', categoryId: 'entite', elementId: 'neutre' },
  { id: 'c04', name: 'Sora (Anti-Forme)', top: 9, right: 8, bottom: 10, left: 8, rarity: 'legendary', categoryId: 'porteur_de_keyblade', elementId: 'tenebres' },
  { id: 'c05', name: 'Roi Mickey (Maître)', top: 8, right: 9, bottom: 9, left: 10, rarity: 'legendary', categoryId: 'porteur_de_keyblade', elementId: 'lumiere' },
  { id: 'c06', name: 'Ansem, Chercheur de Ténèbres', top: 9, right: 9, bottom: 7, left: 10, rarity: 'legendary', categoryId: 'antagoniste', elementId: 'tenebres' },
  { id: 'c07', name: 'Xemnas', top: 10, right: 8, bottom: 9, left: 9, rarity: 'legendary', categoryId: 'organisation_xiii', elementId: 'neant' },
  { id: 'c08', name: 'Roxas (Double Keyblade)', top: 9, right: 10, bottom: 7, left: 9, rarity: 'legendary', categoryId: 'porteur_de_keyblade', elementId: 'lumiere' },
  { id: 'c09', name: 'Terra-Xehanort', top: 8, right: 9, bottom: 10, left: 8, rarity: 'legendary', categoryId: 'antagoniste', elementId: 'tenebres' },
  { id: 'c10', name: 'Maître Aqua', top: 8, right: 10, bottom: 9, left: 8, rarity: 'legendary', categoryId: 'porteur_de_keyblade', elementId: 'lumiere' },
  { id: 'c11', name: 'Ventus-Vanitas', top: 9, right: 8, bottom: 8, left: 10, rarity: 'legendary', categoryId: 'porteur_de_keyblade', elementId: 'tenebres' },
  { id: 'c12', name: 'Sora & Riku (Lien)', top: 10, right: 9, bottom: 9, left: 8, rarity: 'legendary', categoryId: 'porteur_de_keyblade', elementId: 'lumiere' },
  { id: 'c13', name: 'χ-blade', top: 9, right: 10, bottom: 10, left: 9, rarity: 'legendary', categoryId: 'arme_legendaire', elementId: 'neutre' },
  { id: 'c14', name: 'Princesse Kairi', top: 7, right: 9, bottom: 10, left: 9, rarity: 'legendary', categoryId: 'porteur_de_keyblade', elementId: 'lumiere' },
  { id: 'c15', name: 'Volonté Persistante (Terra)', top: 10, right: 8, bottom: 8, left: 9, rarity: 'legendary', categoryId: 'porteur_de_keyblade', elementId: 'neutre' },
  { id: 'c16', name: 'Sora', top: 8, right: 7, bottom: 6, left: 8, rarity: 'epic', categoryId: 'porteur_de_keyblade', elementId: 'lumiere' },
  { id: 'c17', name: 'Riku', top: 7, right: 8, bottom: 8, left: 6, rarity: 'epic', categoryId: 'porteur_de_keyblade', elementId: 'tenebres' },
  { id: 'c18', name: 'Kairi', top: 6, right: 7, bottom: 8, left: 7, rarity: 'epic', categoryId: 'porteur_de_keyblade', elementId: 'lumiere' },
  { id: 'c19', name: 'Roxas', top: 7, right: 8, bottom: 6, left: 7, rarity: 'epic', categoryId: 'porteur_de_keyblade', elementId: 'lumiere' },
  { id: 'c20', name: 'Axel', top: 8, right: 7, bottom: 5, left: 8, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'feu' },
  { id: 'c21', name: 'Xion', top: 6, right: 8, bottom: 7, left: 7, rarity: 'epic', categoryId: 'porteur_de_keyblade', elementId: 'lumiere' },
  { id: 'c22', name: 'Terra', top: 9, right: 6, bottom: 5, left: 7, rarity: 'epic', categoryId: 'porteur_de_keyblade', elementId: 'terre' },
  { id: 'c23', name: 'Ventus', top: 5, right: 8, bottom: 7, left: 8, rarity: 'epic', categoryId: 'porteur_de_keyblade', elementId: 'vent' },
  { id: 'c24', name: 'Aqua', top: 7, right: 7, bottom: 8, left: 6, rarity: 'epic', categoryId: 'porteur_de_keyblade', elementId: 'eau' },
  { id: 'c25', name: 'Vanitas', top: 8, right: 8, bottom: 6, left: 6, rarity: 'epic', categoryId: 'antagoniste', elementId: 'tenebres' },
  { id: 'c26', name: 'Maléfique', top: 7, right: 5, bottom: 8, left: 8, rarity: 'epic', categoryId: 'mechant_disney', elementId: 'tenebres' },
  { id: 'c27', name: 'Sephiroth', top: 9, right: 8, bottom: 5, left: 6, rarity: 'epic', categoryId: 'final_fantasy', elementId: 'tenebres' },
  { id: 'c28', name: 'Cloud', top: 8, right: 7, bottom: 6, left: 7, rarity: 'epic', categoryId: 'final_fantasy', elementId: 'neutre' },
  { id: 'c29', name: 'Saïx', top: 7, right: 6, bottom: 8, left: 7, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'lune' },
  { id: 'c30', name: 'Marluxia', top: 6, right: 8, bottom: 7, left: 7, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'fleur' },
  { id: 'c31', name: 'Larxene', top: 7, right: 7, bottom: 5, left: 9, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'foudre' },
  { id: 'c32', name: 'Luxord', top: 6, right: 7, bottom: 7, left: 8, rarity: 'epic', categoryId: 'organisation_xiii', elementId: 'temps' },
  { id: 'c33', name: 'Hadès', top: 8, right: 6, bottom: 7, left: 7, rarity: 'epic', categoryId: 'mechant_disney', elementId: 'feu' },
  { id: 'c34', name: 'Côté Obscur', top: 9, right: 5, bottom: 7, left: 7, rarity: 'epic', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c35', name: 'Épine du Crépuscule', top: 7, right: 8, bottom: 7, left: 5, rarity: 'epic', categoryId: 'simili', elementId: 'neant' },
  { id: 'c36', name: 'Naminé', top: 5, right: 7, bottom: 9, left: 6, rarity: 'epic', categoryId: 'alliee', elementId: 'lumiere' },
  { id: 'c37', name: 'DiZ / Ansem le Sage', top: 6, right: 6, bottom: 8, left: 8, rarity: 'epic', categoryId: 'allie', elementId: 'neutre' },
  { id: 'c38', name: 'Maître Eraqus', top: 7, right: 8, bottom: 7, left: 6, rarity: 'epic', categoryId: 'porteur_de_keyblade', elementId: 'lumiere' },
  { id: 'c39', name: 'Jeune Xehanort', top: 8, right: 7, bottom: 7, left: 6, rarity: 'epic', categoryId: 'antagoniste', elementId: 'temps' },
  { id: 'c40', name: 'Riku (Mode Obscur)', top: 8, right: 8, bottom: 5, left: 7, rarity: 'epic', categoryId: 'porteur_de_keyblade', elementId: 'tenebres' },
  { id: 'c41', name: 'Donald', top: 4, right: 6, bottom: 5, left: 7, rarity: 'rare', categoryId: 'allie', elementId: 'magie' },
  { id: 'c42', name: 'Dingo', top: 6, right: 4, bottom: 7, left: 5, rarity: 'rare', categoryId: 'allie', elementId: 'neutre' },
  { id: 'c43', name: 'Roi Mickey', top: 6, right: 7, bottom: 5, left: 5, rarity: 'rare', categoryId: 'allie', elementId: 'lumiere' },
  { id: 'c44', name: 'Xigbar', top: 5, right: 7, bottom: 4, left: 6, rarity: 'rare', categoryId: 'organisation_xiii', elementId: 'espace' },
  { id: 'c45', name: 'Xaldin', top: 7, right: 5, bottom: 5, left: 5, rarity: 'rare', categoryId: 'organisation_xiii', elementId: 'vent' },
  { id: 'c46', name: 'Vexen', top: 4, right: 5, bottom: 7, left: 6, rarity: 'rare', categoryId: 'organisation_xiii', elementId: 'glace' },
  { id: 'c47', name: 'Lexaeus', top: 7, right: 3, bottom: 6, left: 6, rarity: 'rare', categoryId: 'organisation_xiii', elementId: 'terre' },
  { id: 'c48', name: 'Zexion', top: 3, right: 7, bottom: 5, left: 7, rarity: 'rare', categoryId: 'organisation_xiii', elementId: 'illusion' },
  { id: 'c49', name: 'Demyx', top: 4, right: 6, bottom: 6, left: 6, rarity: 'rare', categoryId: 'organisation_xiii', elementId: 'eau' },
  { id: 'c50', name: 'Jack Sparrow', top: 5, right: 7, bottom: 5, left: 5, rarity: 'rare', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c51', name: 'Simba', top: 7, right: 5, bottom: 4, left: 6, rarity: 'rare', categoryId: 'invocation', elementId: 'feu' },
  { id: 'c52', name: 'Génie', top: 5, right: 6, bottom: 6, left: 5, rarity: 'rare', categoryId: 'invocation', elementId: 'magie' },
  { id: 'c53', name: 'Stitch', top: 5, right: 6, bottom: 5, left: 6, rarity: 'rare', categoryId: 'invocation', elementId: 'foudre' },
  { id: 'c54', name: 'La Bête', top: 7, right: 4, bottom: 3, left: 7, rarity: 'rare', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c55', name: 'Mulan / Ping', top: 6, right: 5, bottom: 5, left: 6, rarity: 'rare', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c56', name: 'Aladdin', top: 5, right: 6, bottom: 5, left: 6, rarity: 'rare', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c57', name: 'Jack Skellington', top: 4, right: 7, bottom: 6, left: 5, rarity: 'rare', categoryId: 'allie_disney', elementId: 'tenebres' },
  { id: 'c58', name: 'Hercule', top: 7, right: 5, bottom: 5, left: 5, rarity: 'rare', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c59', name: 'Tron', top: 5, right: 6, bottom: 6, left: 5, rarity: 'rare', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c60', name: 'Léon (Squall)', top: 6, right: 6, bottom: 4, left: 6, rarity: 'rare', categoryId: 'final_fantasy', elementId: 'neutre' },
  { id: 'c61', name: 'Yuffie', top: 4, right: 7, bottom: 5, left: 6, rarity: 'rare', categoryId: 'final_fantasy', elementId: 'neutre' },
  { id: 'c62', name: 'Aérith', top: 3, right: 5, bottom: 7, left: 7, rarity: 'rare', categoryId: 'final_fantasy', elementId: 'lumiere' },
  { id: 'c63', name: 'Cid', top: 5, right: 5, bottom: 6, left: 6, rarity: 'rare', categoryId: 'final_fantasy', elementId: 'neutre' },
  { id: 'c64', name: 'Tifa', top: 6, right: 6, bottom: 5, left: 5, rarity: 'rare', categoryId: 'final_fantasy', elementId: 'neutre' },
  { id: 'c65', name: 'Auron', top: 7, right: 5, bottom: 5, left: 5, rarity: 'rare', categoryId: 'final_fantasy', elementId: 'feu' },
  { id: 'c66', name: 'Armure de Garde', top: 6, right: 4, bottom: 6, left: 6, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c67', name: 'Maître Truqueur', top: 5, right: 6, bottom: 5, left: 6, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'feu' },
  { id: 'c68', name: 'Kurt Zisa', top: 6, right: 6, bottom: 6, left: 4, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c69', name: 'Fantôme', top: 4, right: 5, bottom: 7, left: 6, rarity: 'rare', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c70', name: 'Ursula', top: 5, right: 7, bottom: 5, left: 5, rarity: 'rare', categoryId: 'mechant_disney', elementId: 'eau' },
  { id: 'c71', name: 'Pirate Sans-cœur', top: 4, right: 3, bottom: 4, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c72', name: 'Invisible', top: 5, right: 4, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c73', name: 'Wyverne', top: 3, right: 5, bottom: 3, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'vent' },
  { id: 'c74', name: 'Sorcier', top: 2, right: 5, bottom: 4, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'magie' },
  { id: 'c75', name: 'Défenseur', top: 5, right: 2, bottom: 4, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c76', name: 'Étoile Angélique', top: 3, right: 4, bottom: 4, left: 4, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'lumiere' },
  { id: 'c77', name: 'Reflet', top: 4, right: 4, bottom: 3, left: 4, rarity: 'uncommon', categoryId: 'simili', elementId: 'neant' },
  { id: 'c78', name: 'Assassin', top: 5, right: 3, bottom: 2, left: 5, rarity: 'uncommon', categoryId: 'simili', elementId: 'neant' },
  { id: 'c79', name: 'Berserker', top: 5, right: 2, bottom: 4, left: 4, rarity: 'uncommon', categoryId: 'simili', elementId: 'neant' },
  { id: 'c80', name: 'Danseuse', top: 3, right: 5, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'simili', elementId: 'neant' },
  { id: 'c81', name: 'Samouraï', top: 4, right: 4, bottom: 3, left: 4, rarity: 'uncommon', categoryId: 'simili', elementId: 'neant' },
  { id: 'c82', name: 'Joueur', top: 3, right: 3, bottom: 5, left: 4, rarity: 'uncommon', categoryId: 'simili', elementId: 'neant' },
  { id: 'c83', name: "Tireur d'élite", top: 2, right: 5, bottom: 3, left: 5, rarity: 'uncommon', categoryId: 'simili', elementId: 'neant' },
  { id: 'c84', name: 'Inondeur', top: 3, right: 4, bottom: 4, left: 4, rarity: 'uncommon', categoryId: 'nescient', elementId: 'tenebres' },
  { id: 'c85', name: 'Bagarreur', top: 4, right: 4, bottom: 3, left: 4, rarity: 'uncommon', categoryId: 'nescient', elementId: 'neutre' },
  { id: 'c86', name: 'Cogneur', top: 5, right: 3, bottom: 3, left: 4, rarity: 'uncommon', categoryId: 'nescient', elementId: 'neutre' },
  { id: 'c87', name: 'Tic & Tac', top: 2, right: 4, bottom: 5, left: 4, rarity: 'uncommon', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c88', name: 'Picsou', top: 3, right: 5, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c89', name: 'Pluto', top: 3, right: 3, bottom: 4, left: 5, rarity: 'uncommon', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c90', name: 'Fée Clochette', top: 2, right: 5, bottom: 4, left: 4, rarity: 'uncommon', categoryId: 'allie_disney', elementId: 'lumiere' },
  { id: 'c91', name: 'Sébastien', top: 3, right: 4, bottom: 4, left: 4, rarity: 'uncommon', categoryId: 'allie_disney', elementId: 'eau' },
  { id: 'c92', name: 'Mushu', top: 4, right: 4, bottom: 2, left: 5, rarity: 'uncommon', categoryId: 'invocation', elementId: 'feu' },
  { id: 'c93', name: 'Jiminy Cricket', top: 2, right: 3, bottom: 5, left: 5, rarity: 'uncommon', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c94', name: 'Abu', top: 3, right: 5, bottom: 3, left: 4, rarity: 'uncommon', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c95', name: 'Iago', top: 4, right: 4, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c96', name: 'Grand Méchant Loup', top: 4, right: 5, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c97', name: 'Mille-pattes Pot', top: 3, right: 3, bottom: 4, left: 5, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c98', name: 'Furtif Rôdeur', top: 4, right: 4, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c99', name: 'Cage Parasite', top: 3, right: 4, bottom: 5, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c100', name: 'Béhémoth', top: 5, right: 3, bottom: 4, left: 3, rarity: 'uncommon', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c101', name: 'Bambi', top: 2, right: 4, bottom: 4, left: 5, rarity: 'uncommon', categoryId: 'invocation', elementId: 'neutre' },
  { id: 'c102', name: 'Dumbo', top: 4, right: 3, bottom: 5, left: 3, rarity: 'uncommon', categoryId: 'invocation', elementId: 'eau' },
  { id: 'c103', name: 'Meow Wow', top: 3, right: 4, bottom: 4, left: 4, rarity: 'uncommon', categoryId: 'reve_mangeur', elementId: 'neutre' },
  { id: 'c104', name: 'Komory Bat', top: 4, right: 3, bottom: 3, left: 5, rarity: 'uncommon', categoryId: 'reve_mangeur', elementId: 'vent' },
  { id: 'c105', name: 'Neku Sakuraba', top: 4, right: 5, bottom: 3, left: 3, rarity: 'uncommon', categoryId: 'allie_twewy', elementId: 'neutre' },
  { id: 'c106', name: 'Ombre', top: 2, right: 2, bottom: 3, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c107', name: 'Soldat', top: 3, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c108', name: 'Gros Corps', top: 4, right: 1, bottom: 3, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c109', name: 'Nocturne Rouge', top: 1, right: 3, bottom: 2, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'feu' },
  { id: 'c110', name: 'Rhapsodie Bleue', top: 1, right: 3, bottom: 3, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'glace' },
  { id: 'c111', name: 'Opéra Jaune', top: 2, right: 2, bottom: 2, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'foudre' },
  { id: 'c112', name: 'Requiem Vert', top: 1, right: 2, bottom: 4, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'soin' },
  { id: 'c113', name: 'Singe Sauvage', top: 3, right: 3, bottom: 1, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c114', name: 'Singe Bondissant', top: 2, right: 3, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c115', name: 'Bandit', top: 3, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c116', name: 'Gros Bandit', top: 4, right: 1, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'feu' },
  { id: 'c117', name: 'Araignée Tonneau', top: 1, right: 2, bottom: 2, left: 4, rarity: 'common', categoryId: 'sans_coeur', elementId: 'feu' },
  { id: 'c118', name: 'Araignée Pot', top: 2, right: 2, bottom: 3, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c119', name: 'Fantôme Chercheur', top: 1, right: 3, bottom: 3, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c120', name: 'Néon Marin', top: 2, right: 3, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'eau' },
  { id: 'c121', name: 'Zone Protectrice', top: 3, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'eau' },
  { id: 'c122', name: 'Aquatank', top: 3, right: 1, bottom: 3, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'eau' },
  { id: 'c123', name: 'Gargouille', top: 2, right: 3, bottom: 1, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'vent' },
  { id: 'c124', name: 'Boule Noire', top: 3, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c125', name: 'Rampant', top: 2, right: 2, bottom: 2, left: 3, rarity: 'common', categoryId: 'simili', elementId: 'neant' },
  { id: 'c126', name: 'Rampant Rouge', top: 3, right: 2, bottom: 1, left: 3, rarity: 'common', categoryId: 'simili', elementId: 'neant' },
  { id: 'c127', name: 'Moguri', top: 1, right: 3, bottom: 3, left: 2, rarity: 'common', categoryId: 'pnj', elementId: 'neutre' },
  { id: 'c128', name: 'Riri', top: 2, right: 2, bottom: 2, left: 3, rarity: 'common', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c129', name: 'Fifi', top: 2, right: 3, bottom: 2, left: 2, rarity: 'common', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c130', name: 'Loulou', top: 2, right: 2, bottom: 3, left: 2, rarity: 'common', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c131', name: 'Daisy', top: 1, right: 3, bottom: 2, left: 3, rarity: 'common', categoryId: 'allie_disney', elementId: 'neutre' },
  { id: 'c132', name: 'Minnie', top: 2, right: 2, bottom: 3, left: 2, rarity: 'common', categoryId: 'allie_disney', elementId: 'lumiere' },
  { id: 'c133', name: 'Biggs', top: 2, right: 2, bottom: 2, left: 3, rarity: 'common', categoryId: 'pnj', elementId: 'neutre' },
  { id: 'c134', name: 'Wedge', top: 3, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'pnj', elementId: 'neutre' },
  { id: 'c135', name: 'Jessie', top: 2, right: 3, bottom: 2, left: 2, rarity: 'common', categoryId: 'pnj', elementId: 'neutre' },
  { id: 'c136', name: 'Champignon Blanc', top: 1, right: 4, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'magie' },
  { id: 'c137', name: 'Champignon Noir', top: 3, right: 1, bottom: 2, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c138', name: 'Truffe Rare', top: 1, right: 2, bottom: 2, left: 4, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c139', name: 'Crescendo', top: 2, right: 3, bottom: 2, left: 2, rarity: 'common', categoryId: 'simili', elementId: 'neant' },
  { id: 'c140', name: 'Étoile du Matin', top: 3, right: 2, bottom: 3, left: 1, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c141', name: 'Marcheur Nocturne', top: 2, right: 2, bottom: 3, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c142', name: 'Chauve-souris Crochet', top: 2, right: 3, bottom: 1, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'vent' },
  { id: 'c143', name: 'Maître Livre', top: 1, right: 4, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'magie' },
  { id: 'c144', name: 'Soldat Aérien', top: 2, right: 3, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'vent' },
  { id: 'c145', name: 'Chien Enragé', top: 3, right: 2, bottom: 1, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c146', name: 'Fantôme Farceur', top: 1, right: 3, bottom: 2, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'tenebres' },
  { id: 'c147', name: 'Chevalier Spectral', top: 2, right: 2, bottom: 3, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c148', name: 'Robot de Surveillance', top: 2, right: 3, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'neutre' },
  { id: 'c149', name: 'Mitrailleur', top: 3, right: 2, bottom: 2, left: 2, rarity: 'common', categoryId: 'sans_coeur', elementId: 'vent' },
  { id: 'c150', name: 'Bombe Minute', top: 1, right: 2, bottom: 3, left: 3, rarity: 'common', categoryId: 'sans_coeur', elementId: 'feu' },
]

export const cardById: Record<CardId, CardDef> = Object.fromEntries(cardPool.map((card) => [card.id, card]))

export function getCard(cardId: CardId): CardDef {
  const card = cardById[cardId]
  if (!card) {
    throw new Error(`Unknown card: ${cardId}`)
  }
  return card
}
