import type { CardDef, CardId } from '../types'

const kantoPokemonNamesByDexOrder = [
  'Bulbizarre',
  'Herbizarre',
  'Florizarre',
  'Salamèche',
  'Reptincel',
  'Dracaufeu',
  'Carapuce',
  'Carabaffe',
  'Tortank',
  'Chenipan',
  'Chrysacier',
  'Papilusion',
  'Aspicot',
  'Coconfort',
  'Dardargnan',
  'Roucool',
  'Roucoups',
  'Roucarnage',
  'Rattata',
  'Rattatac',
  'Piafabec',
  'Rapasdepic',
  'Abo',
  'Arbok',
  'Pikachu',
  'Raichu',
  'Sabelette',
  'Sablaireau',
  'Nidoran♀',
  'Nidorina',
  'Nidoqueen',
  'Nidoran♂',
  'Nidorino',
  'Nidoking',
  'Mélofée',
  'Mélodelfe',
  'Goupix',
  'Feunard',
  'Rondoudou',
  'Grodoudou',
  'Nosferapti',
  'Nosferalto',
  'Mystherbe',
  'Ortide',
  'Rafflesia',
  'Paras',
  'Parasect',
  'Mimitoss',
  'Aéromite',
  'Taupiqueur',
  'Triopikeur',
  'Miaouss',
  'Persian',
  'Psykokwak',
  'Akwakwak',
  'Férosinge',
  'Colossinge',
  'Caninos',
  'Arcanin',
  'Ptitard',
  'Têtarte',
  'Tartard',
  'Abra',
  'Kadabra',
  'Alakazam',
  'Machoc',
  'Machopeur',
  'Mackogneur',
  'Chétiflor',
  'Boustiflor',
  'Empiflor',
  'Tentacool',
  'Tentacruel',
  'Racaillou',
  'Gravalanch',
  'Grolem',
  'Ponyta',
  'Galopa',
  'Ramoloss',
  'Flagadoss',
  'Magnéti',
  'Magnéton',
  'Canarticho',
  'Doduo',
  'Dodrio',
  'Otaria',
  'Lamantine',
  'Tadmorv',
  'Grotadmorv',
  'Kokiyas',
  'Crustabri',
  'Fantominus',
  'Spectrum',
  'Ectoplasma',
  'Onix',
  'Soporifik',
  'Hypnomade',
  'Krabby',
  'Krabboss',
  'Voltorbe',
  'Électrode',
  'Noeunoeuf',
  'Noadkoko',
  'Osselait',
  'Ossatueur',
  'Kicklee',
  'Tygnon',
  'Excelangue',
  'Smogo',
  'Smogogo',
  'Rhinocorne',
  'Rhinoféros',
  'Leveinard',
  'Saquedeneu',
  'Kangourex',
  'Hypotrempe',
  'Hypocéan',
  'Poissirène',
  'Poissoroy',
  'Stari',
  'Staross',
  'M. Mime',
  'Insécateur',
  'Lippoutou',
  'Élektek',
  'Magmar',
  'Scarabrute',
  'Tauros',
  'Magicarpe',
  'Léviator',
  'Lokhlass',
  'Métamorph',
  'Évoli',
  'Aquali',
  'Voltali',
  'Pyroli',
  'Porygon',
  'Amonita',
  'Amonistar',
  'Kabuto',
  'Kabutops',
  'Ptéra',
  'Ronflex',
  'Artikodin',
  'Électhor',
  'Sulfura',
  'Minidraco',
  'Draco',
  'Dracolosse',
  'Mewtwo',
  'Mew',
] as const

function normalizePokemonName(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/♀/g, 'f')
    .replace(/♂/g, 'm')
    .replace(/[^a-zA-Z0-9]/g, '')
    .toLowerCase()
}

function parseFallbackPokedexNumber(cardId: CardId): number {
  const parsed = Number.parseInt(cardId.slice(1), 10)
  return Number.isFinite(parsed) && parsed > 0 ? parsed : 0
}

const pokedexNumberByNormalizedName = new Map<string, number>(
  kantoPokemonNamesByDexOrder.map((name, index) => [normalizePokemonName(name), index + 1]),
)

export function getCardPokedexNumber(card: Pick<CardDef, 'id' | 'name'>): number {
  const byName = pokedexNumberByNormalizedName.get(normalizePokemonName(card.name))
  return byName ?? parseFallbackPokedexNumber(card.id)
}

export function compareCardsByPokedexNumber(
  leftCard: Pick<CardDef, 'id' | 'name'>,
  rightCard: Pick<CardDef, 'id' | 'name'>,
): number {
  return getCardPokedexNumber(leftCard) - getCardPokedexNumber(rightCard)
}

export function formatCardPokedexNumber(card: Pick<CardDef, 'id' | 'name'>): string {
  return `#${getCardPokedexNumber(card).toString().padStart(3, '0')}`
}
